# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtGol.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(887, 470)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.tab_struc = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_struc.setObjectName("tab_struc")
        self.tab_stable = QtWidgets.QWidget()
        self.tab_stable.setObjectName("tab_stable")
        self.tab_struc.addTab(self.tab_stable, "")
        self.tab_period = QtWidgets.QWidget()
        self.tab_period.setObjectName("tab_period")
        self.tab_struc.addTab(self.tab_period, "")
        self.tab_spaceship = QtWidgets.QWidget()
        self.tab_spaceship.setObjectName("tab_spaceship")
        self.tab_struc.addTab(self.tab_spaceship, "")
        self.gridLayout.addWidget(self.tab_struc, 0, 2, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.sb_xcell = QtWidgets.QSpinBox(self.centralwidget)
        self.sb_xcell.setObjectName("sb_xcell")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sb_xcell)
        self.lb_y_cells = QtWidgets.QLabel(self.centralwidget)
        self.lb_y_cells.setObjectName("lb_y_cells")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lb_y_cells)
        self.sb_ycell = QtWidgets.QSpinBox(self.centralwidget)
        self.sb_ycell.setObjectName("sb_ycell")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sb_ycell)
        self.lb_cell_size = QtWidgets.QLabel(self.centralwidget)
        self.lb_cell_size.setObjectName("lb_cell_size")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lb_cell_size)
        self.sb_sizecell = QtWidgets.QSpinBox(self.centralwidget)
        self.sb_sizecell.setObjectName("sb_sizecell")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sb_sizecell)
        self.lb_speed = QtWidgets.QLabel(self.centralwidget)
        self.lb_speed.setObjectName("lb_speed")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lb_speed)
        self.sl_speed = QtWidgets.QSlider(self.centralwidget)
        self.sl_speed.setMinimum(50)
        self.sl_speed.setMaximum(1000)
        self.sl_speed.setSingleStep(1)
        self.sl_speed.setTracking(False)
        self.sl_speed.setOrientation(QtCore.Qt.Horizontal)
        self.sl_speed.setInvertedAppearance(False)
        self.sl_speed.setInvertedControls(False)
        self.sl_speed.setObjectName("sl_speed")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sl_speed)
        self.lb_x_cells = QtWidgets.QLabel(self.centralwidget)
        self.lb_x_cells.setObjectName("lb_x_cells")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lb_x_cells)
        self.gridLayout.addLayout(self.formLayout, 2, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.canvas = QtWidgets.QGraphicsView(self.centralwidget)
        self.canvas.setEnabled(True)
        self.canvas.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.canvas.setMouseTracking(True)
        self.canvas.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.canvas.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.canvas.setObjectName("canvas")
        self.gridLayout.addWidget(self.canvas, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.bt_quit = QtWidgets.QPushButton(self.centralwidget)
        self.bt_quit.setObjectName("bt_quit")
        self.gridLayout_3.addWidget(self.bt_quit, 2, 2, 1, 1)
        self.bt_start = QtWidgets.QPushButton(self.centralwidget)
        self.bt_start.setAutoDefault(False)
        self.bt_start.setDefault(False)
        self.bt_start.setFlat(False)
        self.bt_start.setObjectName("bt_start")
        self.gridLayout_3.addWidget(self.bt_start, 1, 0, 1, 1)
        self.bt_reset = QtWidgets.QPushButton(self.centralwidget)
        self.bt_reset.setObjectName("bt_reset")
        self.gridLayout_3.addWidget(self.bt_reset, 1, 2, 1, 1)
        self.bt_autogen = QtWidgets.QPushButton(self.centralwidget)
        self.bt_autogen.setObjectName("bt_autogen")
        self.gridLayout_3.addWidget(self.bt_autogen, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tab_struc.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tab_struc.setTabText(self.tab_struc.indexOf(self.tab_stable), _translate("MainWindow", "Stable"))
        self.tab_struc.setTabText(self.tab_struc.indexOf(self.tab_period), _translate("MainWindow", "Periodic"))
        self.tab_struc.setTabText(self.tab_struc.indexOf(self.tab_spaceship), _translate("MainWindow", "Spaceship"))
        self.lb_y_cells.setText(_translate("MainWindow", "Y Cells"))
        self.lb_cell_size.setText(_translate("MainWindow", "Cell Size"))
        self.lb_speed.setText(_translate("MainWindow", "Speed"))
        self.lb_x_cells.setText(_translate("MainWindow", "X Cells"))
        self.bt_quit.setText(_translate("MainWindow", "Quit"))
        self.bt_start.setText(_translate("MainWindow", "Start / Pause"))
        self.bt_reset.setText(_translate("MainWindow", "Reset"))
        self.bt_autogen.setText(_translate("MainWindow", "Gen Auto"))

