# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtGol.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(887, 629)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.canvas = QtWidgets.QGraphicsView(self.centralwidget)
        self.canvas.setGeometry(QtCore.QRect(10, 10, 500, 500))
        self.canvas.setObjectName("canvas")
        self.tab_struc = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_struc.setGeometry(QtCore.QRect(520, 10, 361, 501))
        self.tab_struc.setObjectName("tab_struc")
        self.tab_stable = QtWidgets.QWidget()
        self.tab_stable.setObjectName("tab_stable")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_stable)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 341, 461))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.toolButton_2 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout.addWidget(self.toolButton_2, 1, 0, 1, 1)
        self.toolButton_3 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_3.setObjectName("toolButton_3")
        self.gridLayout.addWidget(self.toolButton_3, 1, 1, 1, 1)
        self.toolButton_6 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_6.setObjectName("toolButton_6")
        self.gridLayout.addWidget(self.toolButton_6, 1, 2, 1, 1)
        self.toolButton = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout.addWidget(self.toolButton, 0, 0, 1, 1)
        self.toolButton_5 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_5.setObjectName("toolButton_5")
        self.gridLayout.addWidget(self.toolButton_5, 0, 2, 1, 1)
        self.toolButton_4 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_4.setObjectName("toolButton_4")
        self.gridLayout.addWidget(self.toolButton_4, 0, 1, 1, 1)
        self.toolButton_7 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_7.setObjectName("toolButton_7")
        self.gridLayout.addWidget(self.toolButton_7, 2, 1, 1, 1)
        self.toolButton_8 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_8.setObjectName("toolButton_8")
        self.gridLayout.addWidget(self.toolButton_8, 2, 0, 1, 1)
        self.toolButton_9 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_9.setObjectName("toolButton_9")
        self.gridLayout.addWidget(self.toolButton_9, 2, 2, 1, 1)
        self.tab_struc.addTab(self.tab_stable, "")
        self.tab_period = QtWidgets.QWidget()
        self.tab_period.setObjectName("tab_period")
        self.tab_struc.addTab(self.tab_period, "")
        self.tab_spaceship = QtWidgets.QWidget()
        self.tab_spaceship.setObjectName("tab_spaceship")
        self.tab_struc.addTab(self.tab_spaceship, "")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(520, 520, 361, 101))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lb_x_cells = QtWidgets.QLabel(self.formLayoutWidget)
        self.lb_x_cells.setObjectName("lb_x_cells")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lb_x_cells)
        self.spinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox.setObjectName("spinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.lb_y_cells = QtWidgets.QLabel(self.formLayoutWidget)
        self.lb_y_cells.setObjectName("lb_y_cells")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lb_y_cells)
        self.spinBox_2 = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox_2.setObjectName("spinBox_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox_2)
        self.lb_cell_size = QtWidgets.QLabel(self.formLayoutWidget)
        self.lb_cell_size.setObjectName("lb_cell_size")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lb_cell_size)
        self.lb_speed = QtWidgets.QLabel(self.formLayoutWidget)
        self.lb_speed.setObjectName("lb_speed")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lb_speed)
        self.spinBox_3 = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox_3.setObjectName("spinBox_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox_3)
        self.horizontalSlider = QtWidgets.QSlider(self.formLayoutWidget)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.horizontalSlider)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 520, 501, 101))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bt_start = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.bt_start.setAutoDefault(False)
        self.bt_start.setDefault(False)
        self.bt_start.setFlat(False)
        self.bt_start.setObjectName("bt_start")
        self.horizontalLayout.addWidget(self.bt_start)
        self.bt_reset = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.bt_reset.setObjectName("bt_reset")
        self.horizontalLayout.addWidget(self.bt_reset)
        self.bt_quit = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.bt_quit.setObjectName("bt_quit")
        self.horizontalLayout.addWidget(self.bt_quit)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tab_struc.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolButton_2.setText(_translate("MainWindow", "..."))
        self.toolButton_3.setText(_translate("MainWindow", "..."))
        self.toolButton_6.setText(_translate("MainWindow", "..."))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.toolButton_5.setText(_translate("MainWindow", "..."))
        self.toolButton_4.setText(_translate("MainWindow", "..."))
        self.toolButton_7.setText(_translate("MainWindow", "..."))
        self.toolButton_8.setText(_translate("MainWindow", "..."))
        self.toolButton_9.setText(_translate("MainWindow", "..."))
        self.tab_struc.setTabText(self.tab_struc.indexOf(self.tab_stable), _translate("MainWindow", "Stable"))
        self.tab_struc.setTabText(self.tab_struc.indexOf(self.tab_period), _translate("MainWindow", "Periodic"))
        self.tab_struc.setTabText(self.tab_struc.indexOf(self.tab_spaceship), _translate("MainWindow", "Spaceship"))
        self.lb_x_cells.setText(_translate("MainWindow", "X Cells"))
        self.lb_y_cells.setText(_translate("MainWindow", "Y Cells"))
        self.lb_cell_size.setText(_translate("MainWindow", "Cell Size"))
        self.lb_speed.setText(_translate("MainWindow", "Speed"))
        self.bt_start.setText(_translate("MainWindow", "Start / Pause"))
        self.bt_reset.setText(_translate("MainWindow", "Reset"))
        self.bt_quit.setText(_translate("MainWindow", "Quit"))

