# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/qtGol.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(607, 353)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.canvas = QtWidgets.QGraphicsView(self.centralwidget)
        self.canvas.setEnabled(True)
        self.canvas.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.canvas.setMouseTracking(True)
        self.canvas.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.canvas.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.canvas.setObjectName("canvas")
        self.gridLayout.addWidget(self.canvas, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.bt_quit = QtWidgets.QPushButton(self.centralwidget)
        self.bt_quit.setObjectName("bt_quit")
        self.gridLayout_3.addWidget(self.bt_quit, 2, 2, 1, 1)
        self.bt_start = QtWidgets.QPushButton(self.centralwidget)
        self.bt_start.setAutoDefault(False)
        self.bt_start.setDefault(False)
        self.bt_start.setFlat(False)
        self.bt_start.setObjectName("bt_start")
        self.gridLayout_3.addWidget(self.bt_start, 1, 0, 1, 1)
        self.bt_reset = QtWidgets.QPushButton(self.centralwidget)
        self.bt_reset.setObjectName("bt_reset")
        self.gridLayout_3.addWidget(self.bt_reset, 1, 2, 1, 1)
        self.bt_autogen = QtWidgets.QPushButton(self.centralwidget)
        self.bt_autogen.setObjectName("bt_autogen")
        self.gridLayout_3.addWidget(self.bt_autogen, 1, 1, 1, 1)
        self.bt_clean = QtWidgets.QPushButton(self.centralwidget)
        self.bt_clean.setObjectName("bt_clean")
        self.gridLayout_3.addWidget(self.bt_clean, 2, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.sb_xcell = QtWidgets.QSpinBox(self.centralwidget)
        self.sb_xcell.setObjectName("sb_xcell")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sb_xcell)
        self.lb_y_cells = QtWidgets.QLabel(self.centralwidget)
        self.lb_y_cells.setObjectName("lb_y_cells")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lb_y_cells)
        self.sb_ycell = QtWidgets.QSpinBox(self.centralwidget)
        self.sb_ycell.setObjectName("sb_ycell")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sb_ycell)
        self.lb_cell_size = QtWidgets.QLabel(self.centralwidget)
        self.lb_cell_size.setObjectName("lb_cell_size")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lb_cell_size)
        self.sb_sizecell = QtWidgets.QSpinBox(self.centralwidget)
        self.sb_sizecell.setObjectName("sb_sizecell")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sb_sizecell)
        self.lb_speed = QtWidgets.QLabel(self.centralwidget)
        self.lb_speed.setObjectName("lb_speed")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lb_speed)
        self.sl_speed = QtWidgets.QSlider(self.centralwidget)
        self.sl_speed.setMinimum(50)
        self.sl_speed.setMaximum(1000)
        self.sl_speed.setSingleStep(10)
        self.sl_speed.setPageStep(50)
        self.sl_speed.setTracking(False)
        self.sl_speed.setOrientation(QtCore.Qt.Horizontal)
        self.sl_speed.setInvertedAppearance(True)
        self.sl_speed.setInvertedControls(True)
        self.sl_speed.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.sl_speed.setTickInterval(50)
        self.sl_speed.setObjectName("sl_speed")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sl_speed)
        self.lb_x_cells = QtWidgets.QLabel(self.centralwidget)
        self.lb_x_cells.setObjectName("lb_x_cells")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lb_x_cells)
        self.gridLayout.addLayout(self.formLayout, 2, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.lb_staticPattern = QtWidgets.QLabel(self.centralwidget)
        self.lb_staticPattern.setObjectName("lb_staticPattern")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lb_staticPattern)
        self.cb_staticPattern = QtWidgets.QComboBox(self.centralwidget)
        self.cb_staticPattern.setObjectName("cb_staticPattern")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cb_staticPattern)
        self.lb_periodicPattern = QtWidgets.QLabel(self.centralwidget)
        self.lb_periodicPattern.setObjectName("lb_periodicPattern")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lb_periodicPattern)
        self.cb_periodicPattern = QtWidgets.QComboBox(self.centralwidget)
        self.cb_periodicPattern.setObjectName("cb_periodicPattern")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cb_periodicPattern)
        self.lb_movingPattern = QtWidgets.QLabel(self.centralwidget)
        self.lb_movingPattern.setObjectName("lb_movingPattern")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lb_movingPattern)
        self.cb_movingPattern = QtWidgets.QComboBox(self.centralwidget)
        self.cb_movingPattern.setObjectName("cb_movingPattern")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cb_movingPattern)
        self.lb_generation = QtWidgets.QLabel(self.centralwidget)
        self.lb_generation.setObjectName("lb_generation")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lb_generation)
        self.lcd_generation = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_generation.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcd_generation.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcd_generation.setSmallDecimalPoint(False)
        self.lcd_generation.setObjectName("lcd_generation")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lcd_generation)
        self.gv_preview = QtWidgets.QGraphicsView(self.centralwidget)
        self.gv_preview.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gv_preview.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gv_preview.setObjectName("gv_preview")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.gv_preview)
        self.gridLayout.addLayout(self.formLayout_2, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bt_quit.setText(_translate("MainWindow", "Quit"))
        self.bt_start.setText(_translate("MainWindow", "Start / Pause"))
        self.bt_reset.setText(_translate("MainWindow", "Reset"))
        self.bt_autogen.setText(_translate("MainWindow", "Gen Auto"))
        self.bt_clean.setText(_translate("MainWindow", "Clean"))
        self.lb_y_cells.setText(_translate("MainWindow", "Y Cells"))
        self.lb_cell_size.setText(_translate("MainWindow", "Cell Size"))
        self.lb_speed.setText(_translate("MainWindow", "Speed"))
        self.lb_x_cells.setText(_translate("MainWindow", "X Cells"))
        self.lb_staticPattern.setText(_translate("MainWindow", "Static Patterns"))
        self.lb_periodicPattern.setText(_translate("MainWindow", "Periodic Pattern"))
        self.lb_movingPattern.setText(_translate("MainWindow", "Moving Pattern"))
        self.lb_generation.setText(_translate("MainWindow", "# Generation"))

